# github action to deploy MyWeb to azure

name: Deploy MyWeb to Azure

on:
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: 'rg-myblog-japanwest-dev-001'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .Net Core
        uses: actions/checkout@v3
        with:
          dotnet-version: '6.0.x'

      - name: Install dependencies
        run: dotnet restore ./src/MyBlog.Web/MyBlog.Web.csproj

      - name: Build
        run: dotnet build ./src/MyBlog.Web/MyBlog.Web.csproj --configuration Release --no-restore

      # publish
      - name: Publish
        run: dotnet publish ./src/MyBlog.Web/MyBlog.Web.csproj --configuration Release --output ./publish
      
      # deploy to azure
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.WEB_PUBLISH_SECRET }}
          package: ./publish
